name: Build artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Artifacts
        run: |
          sudo apt install -y default-jre
          javac Main.java
          jar cvfe switcher.jar Main *.class
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: switcher.jar
          path: switcher.jar
