name: Build artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Artifacts
        run: |
          sudo apt install -y default-jre maven
          mvn package
          mv target/switcher*.jar ./
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: switcher.jar
          path: switcher*.jar
